"""
Tesla Weekly Report → 카카오톡 나에게 보내기
  - Supabase drives 테이블에서 지난 7일치 데이터 집계
  - 매주 월요일 08:00 KST (GitHub Actions cron)
"""

import os
import sys
import requests
import json
from datetime import datetime, timezone, timedelta
from supabase import create_client, Client


# ── 환경변수 ──────────────────────────────────────────────────────────────────
KAKAO_ACCESS_TOKEN = os.environ["KAKAO_ACCESS_TOKEN"]
SUPABASE_URL       = os.environ["SUPABASE_URL"]
SUPABASE_KEY       = os.environ["SUPABASE_KEY"]

KAKAO_MEMO_URL  = "https://kapi.kakao.com/v2/api/talk/memo/default/send"
BATTERY_KWH     = 82.0    # Model Y Long Range 공칭 용량 (kWh)
MILES_TO_KM     = 1.60934


# ── 1. Supabase에서 지난 7일치 데이터 조회 ────────────────────────────────────
def fetch_weekly_data(client: Client) -> list[dict]:
    since = (datetime.now(timezone.utc) - timedelta(days=7)).isoformat()

    result = (
        client.table("drives")
        .select(
            "recorded_at, battery_level, battery_range, "
            "odometer, charge_energy_added, is_charging"
        )
        .gte("recorded_at", since)
        .order("recorded_at", desc=False)
        .execute()
    )

    rows = result.data or []
    print(f"✅ 조회된 레코드 수: {len(rows)}건")
    return rows


# ── 2. 집계 계산 ──────────────────────────────────────────────────────────────
def aggregate(rows: list[dict]) -> dict:
    if not rows:
        return None

    count = len(rows)

    # 총 주행거리: 오도미터 최대 - 최소 (miles → km)
    odometers = [r["odometer"] for r in rows if r.get("odometer") is not None]
    total_km  = (max(odometers) - min(odometers)) * MILES_TO_KM if len(odometers) >= 2 else 0.0

    # 배터리 최저 / 최고
    levels      = [r["battery_level"] for r in rows if r.get("battery_level") is not None]
    battery_min = min(levels) if levels else None
    battery_max = max(levels) if levels else None

    # 평균 전비 (km/kWh)
    # 추정 소비 에너지 = 배터리 레벨 감소량 × BATTERY_KWH / 100 + 충전 에너지 합산
    first_level   = levels[0]  if levels else 0
    last_level    = levels[-1] if levels else 0
    level_drop_kwh = max(0, (first_level - last_level)) * BATTERY_KWH / 100

    charged_kwh = sum(
        r["charge_energy_added"]
        for r in rows
        if r.get("charge_energy_added") and r.get("is_charging")
    )
    total_energy_kwh = level_drop_kwh + charged_kwh

    if total_energy_kwh > 0 and total_km > 0:
        avg_efficiency = round(total_km / total_energy_kwh, 2)
    else:
        # 에너지 추정 불가 시 battery_range/battery_level 평균으로 추산
        ratios = [
            (r["battery_range"] * MILES_TO_KM) / (r["battery_level"] * BATTERY_KWH / 100)
            for r in rows
            if r.get("battery_range") and r.get("battery_level")
        ]
        avg_efficiency = round(sum(ratios) / len(ratios), 2) if ratios else None

    return {
        "count":          count,
        "total_km":       round(total_km, 1),
        "avg_efficiency": avg_efficiency,
        "battery_min":    battery_min,
        "battery_max":    battery_max,
        "period_start":   rows[0]["recorded_at"][:10],
        "period_end":     rows[-1]["recorded_at"][:10],
    }


# ── 3. 카카오톡 나에게 보내기 ─────────────────────────────────────────────────
def send_kakao(stats: dict) -> None:
    efficiency_str = (
        f"{stats['avg_efficiency']} km/kWh"
        if stats["avg_efficiency"]
        else "계산 불가"
    )
    battery_str = (
        f"{stats['battery_min']}% ~ {stats['battery_max']}%"
        if stats["battery_min"] is not None
        else "데이터 없음"
    )

    text = (
        f"🚗 Tesla 주간 리포트\n"
        f"📅 {stats['period_start']} ~ {stats['period_end']}\n"
        f"{'─' * 26}\n"
        f"📍 총 주행거리     {stats['total_km']} km\n"
        f"⚡ 평균 전비       {efficiency_str}\n"
        f"🔋 배터리 범위     {battery_str}\n"
        f"📊 데이터 수집     {stats['count']}회\n"
        f"{'─' * 26}\n"
        f"Generated by Tesla Collector 🤖"
    )

    template = {
        "object_type": "text",
        "text":        text,
        "link": {
            "web_url":        "https://my-tesla-trip.vercel.app",
            "mobile_web_url": "https://my-tesla-trip.vercel.app",
        },
    }

    resp = requests.post(
        KAKAO_MEMO_URL,
        headers={
            "Authorization": f"Bearer {KAKAO_ACCESS_TOKEN}",
            "Content-Type":  "application/x-www-form-urlencoded",
        },
        data={"template_object": json.dumps(template, ensure_ascii=False)},
        timeout=15,
    )
    resp.raise_for_status()

    result_code = resp.json().get("result_code")
    if result_code != 0:
        raise RuntimeError(f"카카오 전송 실패 (result_code={result_code}): {resp.text}")

    print("✅ 카카오톡 전송 완료")


# ── 메인 ──────────────────────────────────────────────────────────────────────
def main():
    now_kst = datetime.now(timezone.utc) + timedelta(hours=9)
    print(f"\n{'='*50}")
    print(f"  Tesla 주간 리포트: {now_kst.strftime('%Y-%m-%d %H:%M KST')}")
    print(f"{'='*50}\n")

    try:
        client = create_client(SUPABASE_URL, SUPABASE_KEY)
        rows   = fetch_weekly_data(client)

        if not rows:
            print("⚠️  지난 7일간 수집된 데이터가 없습니다. 카카오톡 전송을 건너뜁니다.")
            sys.exit(0)

        stats = aggregate(rows)

        print("\n📋 집계 결과:")
        for k, v in stats.items():
            print(f"   {k}: {v}")

        send_kakao(stats)
        print("\n🎉 주간 리포트 완료!\n")

    except Exception as e:
        print(f"\n❌ 오류: {e}\n")
        sys.exit(1)


if __name__ == "__main__":
    main()
```

---

## GitHub Secrets 추가 목록
```
KAKAO_ACCESS_TOKEN   ← 카카오 개발자 콘솔 > 내 앱 > 보안 > 액세스 토큰
SUPABASE_URL         ← 기존 유지
SUPABASE_KEY         ← 기존 유지