"""
Tesla Weekly Report → KakaoTalk "Send to Me"
  - Aggregate last 7 days of data from Supabase drives table
  - Runs every Monday 08:00 KST via GitHub Actions cron
"""

import os
import sys
import requests
import json
from datetime import datetime, timezone, timedelta
from supabase import create_client, Client


# -- Environment Variables ----------------------------------------------------
KAKAO_ACCESS_TOKEN = os.environ["KAKAO_ACCESS_TOKEN"]
SUPABASE_URL       = os.environ["SUPABASE_URL"]
SUPABASE_KEY       = os.environ["SUPABASE_KEY"]

KAKAO_MEMO_URL = "https://kapi.kakao.com/v2/api/talk/memo/default/send"
BATTERY_KWH    = 82.0     # Model Y Long Range nominal capacity (kWh)
MILES_TO_KM    = 1.60934


# -- 1. Fetch Last 7 Days from Supabase ---------------------------------------
def fetch_weekly_data(client: Client) -> list[dict]:
    since = (datetime.now(timezone.utc) - timedelta(days=7)).isoformat()

    result = (
        client.table("drives")
        .select(
            "recorded_at, battery_level, battery_range, "
            "odometer, charge_energy_added, is_charging"
        )
        .gte("recorded_at", since)
        .order("recorded_at", desc=False)
        .execute()
    )

    rows = result.data or []
    print(f"Records fetched: {len(rows)}")
    return rows


# -- 2. Aggregate Stats -------------------------------------------------------
def aggregate(rows: list[dict]) -> dict:
    if not rows:
        return None

    count = len(rows)

    # Total distance: max odometer - min odometer (miles -> km)
    odometers = [r["odometer"] for r in rows if r.get("odometer") is not None]
    total_km  = (max(odometers) - min(odometers)) * MILES_TO_KM if len(odometers) >= 2 else 0.0

    # Battery min / max
    levels      = [r["battery_level"] for r in rows if r.get("battery_level") is not None]
    battery_min = min(levels) if levels else None
    battery_max = max(levels) if levels else None

    # Average efficiency (km/kWh)
    # Estimated energy = battery level drop * capacity + charged energy
    first_level    = levels[0]  if levels else 0
    last_level     = levels[-1] if levels else 0
    level_drop_kwh = max(0, (first_level - last_level)) * BATTERY_KWH / 100

    charged_kwh = sum(
        r["charge_energy_added"]
        for r in rows
        if r.get("charge_energy_added") and r.get("is_charging")
    )
    total_energy_kwh = level_drop_kwh + charged_kwh

    if total_energy_kwh > 0 and total_km > 0:
        avg_efficiency = round(total_km / total_energy_kwh, 2)
    else:
        # Fallback: estimate from battery_range / battery_level ratio
        ratios = [
            (r["battery_range"] * MILES_TO_KM) / (r["battery_level"] * BATTERY_KWH / 100)
            for r in rows
            if r.get("battery_range") and r.get("battery_level")
        ]
        avg_efficiency = round(sum(ratios) / len(ratios), 2) if ratios else None

    return {
        "count":          count,
        "total_km":       round(total_km, 1),
        "avg_efficiency": avg_efficiency,
        "battery_min":    battery_min,
        "battery_max":    battery_max,
        "period_start":   rows[0]["recorded_at"][:10],
        "period_end":     rows[-1]["recorded_at"][:10],
    }


# -- 3. Send KakaoTalk "Send to Me" -------------------------------------------
def send_kakao(stats: dict) -> None:
    efficiency_str = (
        f"{stats['avg_efficiency']} km/kWh"
        if stats["avg_efficiency"]
        else "N/A"
    )
    battery_str = (
        f"{stats['battery_min']}% ~ {stats['battery_max']}%"
        if stats["battery_min"] is not None
        else "No data"
    )

    text = (
        f"🚗 Tesla Weekly Report\n"
        f"📅 {stats['period_start']} ~ {stats['period_end']}\n"
        f"{'─' * 26}\n"
        f"📍 Total Distance     {stats['total_km']} km\n"
        f"⚡ Avg Efficiency     {efficiency_str}\n"
        f"🔋 Battery Range      {battery_str}\n"
        f"📊 Data Points        {stats['count']}\n"
        f"{'─' * 26}\n"
        f"Generated by Tesla Collector 🤖"
    )

    template = {
        "object_type": "text",
        "text":        text,
        "link": {
            "web_url":        "https://my-tesla-trip.vercel.app",
            "mobile_web_url": "https://my-tesla-trip.vercel.app",
        },
    }

    resp = requests.post(
        KAKAO_MEMO_URL,
        headers={
            "Authorization": f"Bearer {KAKAO_ACCESS_TOKEN}",
            "Content-Type":  "application/x-www-form-urlencoded",
        },
        data={"template_object": json.dumps(template, ensure_ascii=False)},
        timeout=15,
    )
    resp.raise_for_status()

    result_code = resp.json().get("result_code")
    if result_code != 0:
        raise RuntimeError(f"KakaoTalk send failed (result_code={result_code}): {resp.text}")

    print("KakaoTalk message sent successfully")


# -- Main ---------------------------------------------------------------------
def main():
    now_kst = datetime.now(timezone.utc) + timedelta(hours=9)
    print(f"\n{'='*50}")
    print(f"  Tesla Weekly Report: {now_kst.strftime('%Y-%m-%d %H:%M KST')}")
    print(f"{'='*50}\n")

    try:
        client = create_client(SUPABASE_URL, SUPABASE_KEY)
        rows   = fetch_weekly_data(client)

        if not rows:
            print("No data collected in the last 7 days. Skipping KakaoTalk.")
            sys.exit(0)

        stats = aggregate(rows)

        print("\nAggregated Stats:")
        for k, v in stats.items():
            print(f"   {k}: {v}")

        send_kakao(stats)
        print("\nWeekly report complete.\n")

    except Exception as e:
        print(f"\nError: {e}\n")
        sys.exit(1)


if __name__ == "__main__":
    main()
